name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: api.timos.design
          username: root
          password: ${{ secrets.PW }}
          script: |
            cd /root/Timos-Dev/backend
            git stash
            git pull
            npm config set ignore-scripts true
            npm i --production
            npm config set ignore-scripts false
            npm run build
            pm2 restart Timos-Dev
