name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: git pull, build and deploy
        run: |
          echo "Starte deploy",
          sshpass -p ${{ secrets.pw }} ssh root@api.timos.design -o StrictHostKeyChecking=no < ./deploy.bash
